CREATE TABLE IF NOT EXISTS kernel_trigger_executions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    trigger_id INT UNSIGNED NULL,
    module VARCHAR(100) NOT NULL,
    event_key VARCHAR(255) NOT NULL,
    capability_id VARCHAR(255) NOT NULL,
    provider VARCHAR(100) DEFAULT NULL,
    status VARCHAR(40) NOT NULL,
    request_id VARCHAR(128) DEFAULT NULL,
    correlation_id VARCHAR(64) DEFAULT NULL,
    external_reference VARCHAR(191) DEFAULT NULL,
    duration_ms INT UNSIGNED DEFAULT NULL,
    error_message TEXT DEFAULT NULL,
    event_payload JSON DEFAULT NULL,
    capability_payload JSON DEFAULT NULL,
    result_payload JSON DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_trigger_created (trigger_id, created_at),
    KEY idx_event_created (event_key, created_at),
    KEY idx_capability_created (capability_id, created_at),
    KEY idx_status_created (status, created_at),
    KEY idx_correlation_created (correlation_id, created_at),
    KEY idx_request_created (request_id, created_at),
    KEY idx_external_reference_created (external_reference, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;