<?php

declare(strict_types=1);

return [
    'GET' => [
        '/' => 'cms-akira-shell:akiraPublicHome',
        '/posts' => 'cms-akira-shell:akiraPublicPostList',
        '/posts/{slug}' => 'cms-akira-shell:akiraPublicPostSingle',
        '/sitemap.xml' => 'cms-akira-shell:akiraPublicSitemap',
        '/robots.txt' => 'cms-akira-shell:akiraPublicRobots',
        '/cms-akira-theme' => 'cms-akira-shell:akiraShellThemeStudio',
        '/cms-akira-shell' => 'cms-akira-shell:akiraShellDashboard',
        '/cms-akira-shell/login' => 'cms-akira-shell:akiraShellLogin',
        '/cms-akira-shell/posts' => 'cms-akira-shell:akiraShellPostList',
        '/cms-akira-shell/posts/new' => 'cms-akira-shell:akiraShellPostCreateForm',
        '/cms-akira-shell/posts/{slug}/edit' => 'cms-akira-shell:akiraShellPostEditForm',
        '/cms-akira-shell/categories' => 'cms-akira-shell:akiraShellCategoryList',
        '/cms-akira-shell/content-types' => 'cms-akira-shell:akiraShellContentTypeList',
        '/cms-akira-shell/media' => 'cms-akira-shell:akiraShellMediaList',
        '/cms-akira-shell/permissions' => 'cms-akira-shell:akiraShellPermissions',
        '/cms-akira-shell/authority' => 'cms-akira-shell:akiraShellAuthority',
        '/cms-akira-shell/provenance' => 'cms-akira-shell:akiraShellProvenance',
        '/cms-akira-shell/modules' => 'cms-akira-shell:akiraShellModules',
        '/cms-akira-shell/workflow' => 'cms-akira-shell:akiraShellWorkflowConsole',
        '/cms-akira-shell/search' => 'cms-akira-shell:akiraShellSearch',
        '/cms-akira-shell/backups' => 'cms-akira-shell:akiraShellBackups',
        '/cms-akira-shell/redirects' => 'cms-akira-shell:akiraShellRedirects',
        '/cms-akira-shell/settings' => 'cms-akira-shell:akiraShellSettings',
        '/cms-akira-shell/users' => 'cms-akira-shell:akiraShellUsers',
        '/cms-akira-shell/compositions' => 'cms-akira-shell:akiraShellCompositions',
        '/cms-akira-shell/compositions/{key}/edit' => 'cms-akira-shell:akiraShellCompositionEdit',
        '/cms-akira-shell/health' => 'cms-akira-shell:akiraShellModuleHealth',
        '/cms-akira-shell/forbidden' => 'cms-akira-shell:akiraShellForbidden',
    ],
    'POST' => [
        '/cms-akira-shell/posts' => 'cms-akira-shell:akiraShellPostCreate',
        '/cms-akira-shell/posts/{slug}' => 'cms-akira-shell:akiraShellPostUpdate',
        '/cms-akira-shell/posts/{slug}/taxonomies' => 'cms-akira-shell:akiraShellPostSetTaxonomies',
        '/cms-akira-shell/posts/{slug}/revisions/{revision_no}/revert' => 'cms-akira-shell:akiraShellPostRevisionRevert',
        '/cms-akira-shell/posts/{slug}/workflow' => 'cms-akira-shell:akiraShellPostWorkflowTransition',
        '/cms-akira-shell/posts/{slug}/delete' => 'cms-akira-shell:akiraShellPostDelete',
        '/cms-akira-shell/categories' => 'cms-akira-shell:akiraShellCategoryCreate',
        '/cms-akira-shell/categories/{id}' => 'cms-akira-shell:akiraShellCategoryUpdate',
        '/cms-akira-shell/categories/{id}/delete' => 'cms-akira-shell:akiraShellCategoryDelete',
        '/cms-akira-shell/content-types' => 'cms-akira-shell:akiraShellContentTypeCreate',
        '/cms-akira-shell/content-types/{id}' => 'cms-akira-shell:akiraShellContentTypeUpdate',
        '/cms-akira-shell/content-types/{id}/delete' => 'cms-akira-shell:akiraShellContentTypeDelete',
        '/cms-akira-shell/media' => 'cms-akira-shell:akiraShellMediaUpload',
        '/cms-akira-shell/media/{media_key}/delete-request' => 'cms-akira-shell:akiraShellMediaDeleteRequest',
        '/cms-akira-shell/media/{media_key}/delete-cancel' => 'cms-akira-shell:akiraShellMediaDeleteCancel',
        '/cms-akira-shell/media/{media_key}/delete' => 'cms-akira-shell:akiraShellMediaDelete',
        '/cms-akira-shell/permissions' => 'cms-akira-shell:akiraShellPermissionUpdate',
        '/cms-akira-shell/modules/{module_id}' => 'cms-akira-shell:akiraShellModuleManage',
        '/cms-akira-shell/workflow/{entity_key}/transition' => 'cms-akira-shell:akiraShellWorkflowConsoleTransition',
        '/cms-akira-shell/search/rebuild' => 'cms-akira-shell:akiraShellSearchRebuild',
        '/cms-akira-shell/backups' => 'cms-akira-shell:akiraShellBackupCreate',
        '/cms-akira-shell/redirects' => 'cms-akira-shell:akiraShellRedirectCreate',
        '/cms-akira-shell/exports' => 'cms-akira-shell:akiraShellExportCreate',
        '/cms-akira-shell/settings' => 'cms-akira-shell:akiraShellSettingsUpdate',
        '/cms-akira-shell/users/{id}/role' => 'cms-akira-shell:akiraShellUserUpdateRole',
        '/cms-akira-shell/users/{id}/active' => 'cms-akira-shell:akiraShellUserSetActive',
        '/cms-akira-shell/users/{id}/revoke' => 'cms-akira-shell:akiraShellUserRevokeSessions',
    ],
];
