<?php

declare(strict_types=1);

namespace Ikabud\Kernel\Workbench\Graph;

final class SpecGenerator
{
    private array $generatedFiles = [];

    private array $entityConfig = [
        "pal.project"  => ["path" => "projects", "seedId" => "project_id", "list" => true, "detail" => true, "edit" => true, "field" => "title",  "actions" => ["save-as-draft", "submit-for-approval"], "uploadField" => "#mockup-file", "uploadTrigger" => "change", "uploadAttachId" => "#mockup-attachment-id"],
        "pal.client"   => ["path" => "clients",   "seedId" => "client_id",  "list" => true, "detail" => true, "edit" => true, "field" => "name",   "actions" => ["save"]],
        "pal.approval" => ["path" => "approvals", "seedId" => null,        "list" => true, "detail" => false, "edit" => false],
        "pal.expense"  => ["path" => "expenses",  "seedId" => null,        "list" => true, "detail" => true, "edit" => true, "field" => "particulars", "actions" => ["save-as-draft"]],
        "pal.purchase" => ["path" => "purchases", "seedId" => null,        "list" => true, "detail" => true, "edit" => true, "field" => "particulars", "actions" => ["save-as-draft"]],
        "pal.issuance" => ["path" => "material-issuance", "seedId" => null, "list" => true, "detail" => true, "edit" => true, "field" => "particulars", "actions" => ["save-as-draft"]],
    ];

    public function __construct(
        private readonly string $moduleId,
        private readonly string $projectRoot,
        private readonly string $outputDir,
    ) {}

    public function generateAll(array $paths): array
    {
        $this->generatedFiles = [];
        if (!is_dir($this->outputDir) && !mkdir($this->outputDir, 0755, true)) return [];
        $byType = [];
        foreach ($paths as $p) { $byType[$p["type"]][] = $p; }
        foreach ($byType as $type => $typePaths) {
            $filtered = array_filter($typePaths, fn($p) => $this->pathIsValid($p));
            if (empty($filtered)) continue;
            $spec = $this->generateSpec($type, $filtered);
            if ($spec === null) continue;
            $filename = "generated-" . $type . ".spec.js";
            file_put_contents($this->outputDir . "/" . $filename, $spec);
            $this->generatedFiles[] = $this->outputDir . "/" . $filename;
        }
        return $this->generatedFiles;
    }

    private function pathIsValid(array $p): bool
    {
        $entity = $p["entity"] ?? "";
        $type = $p["type"] ?? "";
        $cfg = $this->entityConfig[$entity] ?? null;
        if ($cfg === null) return true;
        return match ($type) {
            "entity_detail" => $cfg["detail"] ?? false,
            "entity_edit" => $cfg["edit"] ?? false,
            "entity_list" => $cfg["list"] ?? false,
            default => true,
        };
    }

    private function generateSpec(string $type, array $paths): ?string
    {
        $Q = chr(39);
        $lines = [];
        $mp = "project-audit-ledger";

        $lines[] = "/** Auto-generated by ARK Workbench Scanner */";
        $lines[] = "var { test, expect } = require(" . $Q . "../../../../WorkbenchFixture" . $Q . ");";
        $lines[] = "var execSync = require(" . $Q . "child_process" . $Q . ").execSync;";
        $lines[] = "var path = require(" . $Q . "path" . $Q . ");";
        $lines[] = "var SEED = path.resolve(__dirname, " . $Q . "../../../../../pal/pal_seed_interactive.php" . $Q . ");";
        $lines[] = "var TENANT = process.env.PAL_TEST_TENANT || " . $Q . "502" . $Q . ";";
        $lines[] = "";
        $lines[] = "async function goTo(page, url) {";
        $lines[] = "    await page.goto(url);";
        $ds = $Q . "[data-wb-component=\"app-shell\"]" . $Q;
        $lines[] = "    await page.waitForSelector(" . $ds . ", { timeout: 15000 });";
        $lines[] = "}";
        $lines[] = "";

        $lines[] = "test.describe(" . $Q . "pal:generated-" . $type . $Q . ", function () {";
        $lines[] = "    test.afterAll(function () { try { execSync(" . $Q . "php " . $Q . " + SEED + " . $Q . " --cleanup --tenant=" . $Q . " + TENANT, { timeout: 10000 }); } catch (e) {} });";
        $lines[] = "";

        foreach ($paths as $i => $p) {
            $label = $p["label"] ?? "path-" . $i;
            $entity = $p["entity"] ?? "";
            $cfg = $this->entityConfig[$entity] ?? null;
            $testName = $this->sanitize($label);
            $seedExpr = ($cfg && $cfg["seedId"]) ? "seed." . $cfg["seedId"] : "seed.project_id";

            $lines[] = "    test(" . $Q . $testName . $Q . ", async function ({ page, integrity }) {";
            $lines[] = "        test.setTimeout(30000);";
            $lines[] = "        var base = " . $Q . "/admin/" . $mp . $Q . ";";
            $lines[] = "        var seed, pid;";
            $lines[] = "        var out = execSync(" . $Q . "php " . $Q . " + SEED + " . $Q . " --tenant=" . $Q . " + TENANT, { encoding: " . $Q . "utf-8" . $Q . ", timeout: 15000 });";
            $lines[] = "        seed = JSON.parse(out);";
            $lines[] = "        if (!seed.ok) { integrity.gap(" . $Q . "Seed failed" . $Q . "); return; }";
            $lines[] = "        pid = " . $seedExpr . ";";
            $lines[] = "        if (!pid) { integrity.gap(" . $Q . "No entity ID" . $Q . "); return; }";

            switch ($type) {
                case "entity_list":
                    $this->appendListTest($lines, $entity, $Q);
                    break;
                case "entity_detail":
                    $this->appendDetailTest($lines, $entity, $Q);
                    break;
                case "entity_edit":
                    $this->appendEditTest($lines, $entity, $cfg, $Q);
                    break;
                case "action":
                    $lines[] = "        await goTo(page, base + " . $Q . "/" . $this->entityPath($entity ?: "pal.project") . "/" . $Q . " + pid + " . $Q . "?disyl_nocache=1" . $Q . ");";
                    $lines[] = "        var body = await page.locator(" . $Q . "#wb-main" . $Q . ").textContent();";
                    $lines[] = "        if (body.indexOf(pid.toString()) < 0) { integrity.gap(" . $Q . "Entity ID missing" . $Q . "); }";
                    break;
                case "transition":
                    $this->appendTransitionTest($lines, $p, $Q);
                    break;
            }

            $lines[] = "    });";
            $lines[] = "";
        }

        $lines[] = "});";
        return implode("\n", $lines);
    }

    private function appendListTest(array &$lines, string $entity, string $Q): void
    {
        $ep = $this->entityPath($entity);
        $lines[] = "        await goTo(page, base + " . $Q . "/" . $ep . $Q . ");";
        $lines[] = "        var listEl = page.locator(" . $Q . "[data-ikb-list], [data-wb-list]" . $Q . ").first();";
        $lines[] = "        if (await listEl.count() === 0) { integrity.gap(" . $Q . "No list for " . $entity . $Q . "); return; }";
        $lines[] = "        var cnt = await listEl.locator(" . $Q . "tbody tr" . $Q . ").count();";
        $lines[] = "        if (cnt === 0) { integrity.gap(" . $Q . "List empty for " . $entity . $Q . "); }";
        $lines[] = "        else { console.log(" . $Q . "  " . $ep . " list: " . $Q . " + cnt + " . $Q . " rows" . $Q . "); }";
    }

    private function appendDetailTest(array &$lines, string $entity, string $Q): void
    {
        $ep = $this->entityPath($entity);
        $dsel = $Q . "[data-wb-component=\"detail-header\"]" . $Q;
        $lines[] = "        await goTo(page, base + " . $Q . "/" . $ep . "/" . $Q . " + pid + " . $Q . "?disyl_nocache=1&wb_inspect=1" . $Q . ");";
        $lines[] = "        if (await page.locator(" . $dsel . ").count() === 0) { integrity.gap(" . $Q . "No detail for " . $entity . $Q . "); return; }";
        $lines[] = "        var m = await page.evaluate(function () { return window.__wbManifest; });";
        $lines[] = "        if (m && m.status === null) { integrity.gap(" . $Q . "Missing status on " . $entity . $Q . "); }";
        $lines[] = "        else if (m) { console.log(" . $Q . "  Status: " . $Q . " + m.status); }";
        $lines[] = "        // Semantic: validate images via HTTP/MIME (catches 404, 403, wrong MIME)";
        $lines[] = "        var imgs = page.locator(\"#wb-main img\");";
        $lines[] = "        var imgCount = await imgs.count();";
        $lines[] = "        for (var ii = 0; ii < imgCount; ii++) {";
        $lines[] = "            var img = imgs.nth(ii);";
        $lines[] = "            var src = await img.getAttribute(\"src\");";
        $lines[] = "            if (!src) continue;";
        $lines[] = "            var imgUrl = new URL(src, page.url()).toString();";
        $lines[] = "            var resp = await page.request.get(imgUrl);";
        $lines[] = "            var ct = (resp.headers()[\"content-type\"] || \"\").toLowerCase();";
        $lines[] = "            if (resp.status() >= 400 || ct.indexOf(\"image/\") !== 0) {";
        $lines[] = "                integrity.issue({kind:\"broken-image\",severity:\"major\",where:imgUrl,detail:\"HTTP \" + resp.status() + \" CT: \" + ct,recommendation:\"Verify attachment download handler, storage permissions and MIME headers.\"});";
        $lines[] = "            } else {";
        $lines[] = "                console.log(\"  Image OK: \" + imgUrl.substring(0, 60));";
        $lines[] = "            }";
        $lines[] = "        }";
    }

    private function appendEditTest(array &$lines, string $entity, ?array $cfg, string $Q): void
    {
        $ep = $this->entityPath($entity);
        $field = ($cfg["field"] ?? "title");
        $lines[] = "        await goTo(page, base + " . $Q . "/" . $ep . "/" . $Q . " + pid + " . $Q . "/edit?disyl_nocache=1" . $Q . ");";
        $lines[] = "        var m = await page.evaluate(function () { return window.__wbManifest; });";
        $lines[] = "        if (m && m.actions && m.actions.length > 0) {";
        $checks = [];
        foreach (($cfg["actions"] ?? ["save"]) as $ak) {
            $checks[] = "m.actions.some(function(a) { return a.key.indexOf(" . $Q . $ak . $Q . ") >= 0; })";
        }
        $lines[] = "            var checks = [" . implode(", ", $checks) . "];";
        $lines[] = "            var allFound = checks.every(function(c) { return c; });";
        $lines[] = "            if (!allFound) { integrity.gap(" . $Q . "Missing action(s) on " . $entity . $Q . "); }";
        $lines[] = "            else { console.log(" . $Q . "  " . $ep . " edit: " . $Q . " + JSON.stringify(m.actions.map(function(a){return a.key;}))); }";
        $lines[] = "        } else { integrity.gap(" . $Q . "No actions on " . $entity . $Q . "); }";
        $qf = $Q . $field . $Q;
        $D = chr(34);
        $lines[] = "        var fld = page.locator(" . $Q . "input[name=" . $D . $field . $D . "]" . $Q . ");";
        $lines[] = "        if (await fld.count() > 0) {";
        $lines[] = "            var val = await fld.inputValue();";
        $lines[] = "            if (!val) { integrity.gap(" . $Q . $entity . " " . $field . " empty" . $Q . "); }";
        $lines[] = "        }";
    }

    private function appendTransitionTest(array &$lines, array $p, string $Q): void
    {
        $to = $p["to"];
        $from = $p["from"];
        $lines[] = "        var result = await page.evaluate(async function(opts) {";
        $lines[] = "            var fd = new URLSearchParams();";
        $lines[] = "            fd.append(" . $Q . "status" . $Q . ", opts.toStatus);";
        $lines[] = "            var r = await fetch(" . $Q . "/api/v1/" . $this->moduleId . "/projects/" . $Q . " + opts.pid + " . $Q . "/status" . $Q . ",";
        $lines[] = "                { method: " . $Q . "POST" . $Q . ", body: fd, headers: { " . $Q . "Content-Type" . $Q . ": " . $Q . "application/x-www-form-urlencoded" . $Q . " } });";
        $lines[] = "            return { ok: (await r.json()).ok, http: r.status };";
        $lines[] = "        }, { pid: pid, toStatus: " . $Q . $to . $Q . " });";
        $lines[] = "        if (!result.ok) {";
        $lines[] = "            integrity.gap(" . $Q . "Transition " . $from . "->" . $to . " HTTP " . $Q . " + result.http);";
        $lines[] = "        } else {";
        $lines[] = "            await goTo(page, base + " . $Q . "/projects/" . $Q . " + pid + " . $Q . "?disyl_nocache=1&wb_inspect=1" . $Q . ");";
        $lines[] = "            var m = await page.evaluate(function () { return window.__wbManifest; });";
        $lines[] = "            if (m && m.status !== " . $Q . $to . $Q . ") { integrity.gap(" . $Q . "Expected " . $to . " got " . $Q . " + (m ? m.status : null)); }";
        $lines[] = "            else { console.log(" . $Q . "  " . $from . "->" . $to . ": " . $Q . " + (m ? m.status : null)); }";
        $lines[] = "        }";
    }

    private function entityPath(string $entity): string
    {
        $cfg = $this->entityConfig[$entity] ?? null;
        return $cfg ? $cfg["path"] : str_replace(".", "/", $entity);
    }

    private function sanitize(string $name): string
    {
        $name = str_replace(["\u2192", ":", "/", "\\"], [" to ", " ", "-", "-"], $name);
        $name = preg_replace("/[^a-zA-Z0-9 _-]/", "", $name) ?? $name;
        return trim(substr($name, 0, 80));
    }
}