<?php

declare(strict_types=1);

namespace Harpp\Services;

use Ikabud\Kernel\Contracts\ModuleDB;
use PDO;
use Throwable;

/** Additive Phase 1 collaboration foundation. UI enforcement remains feature-gated. */
final class HarppCollaborationService
{
    private HarppFoundationService $foundation;
    public function __construct(private ModuleDB $database){$this->foundation=new HarppFoundationService($database);}

    public function listWorkspaces(array $actor): HarppServiceResult
    {
        $tenantWide=$this->admin($actor);
        $sql="SELECT w.id,w.workspace_key,w.name,w.status,w.version,w.created_at,w.updated_at,m.roles,m.status membership_status FROM harpp_workspaces w ".($tenantWide?'LEFT':'INNER')." JOIN harpp_workspace_memberships m ON m.workspace_id=w.id AND m.user_id=:user AND m.status='active'".($tenantWide?'':" WHERE m.id IS NOT NULL")." ORDER BY w.name,w.id";
        $s=$this->database->prepare($sql);$s->execute([':user'=>(int)$actor['id']]);return HarppServiceResult::success(['workspaces'=>$s->fetchAll(PDO::FETCH_ASSOC)]);
    }

    public function manageWorkspace(array $actor,array $input): HarppServiceResult
    {
        $action=(string)($input['action']??'create');
        $requestedWorkspace=(int)($input['workspace_id']??0);$actorId=(int)($actor['id']??0);if($action==='create'&&!$this->admin($actor))return HarppServiceResult::failure('Owner or admin access is required to create workspaces.',403);if($action==='delegation'){if(($actor['role']??'')!=='owner'&&((int)($input['from_user_id']??0)!==$actorId||!$this->workspaceMember($requestedWorkspace,$actorId)))return HarppServiceResult::failure('A member may delegate only their own workspace approval authority.',403);}elseif($action!=='create'&&!$this->admin($actor)&&!$this->workspaceRole($requestedWorkspace,$actorId,'manager'))return HarppServiceResult::failure('Workspace manager access is required.',403);
        try{$this->database->beginTransaction();
            if($action==='create'){$key=strtolower(trim((string)($input['workspace_key']??'')));$name=trim(strip_tags((string)($input['name']??'')));if(!preg_match('/^[a-z0-9][a-z0-9._-]{2,190}$/',$key)||$name===''||strlen($name)>255)throw new \InvalidArgumentException('Valid workspace_key and name are required.');$s=$this->database->prepare("INSERT INTO harpp_workspaces(workspace_key,name,status,created_by,version,created_at,updated_at) VALUES(:key,:name,'active',:actor,1,NOW(6),NOW(6))");$s->execute([':key'=>$key,':name'=>$name,':actor'=>(int)$actor['id']]);$workspace=(int)$this->database->lastInsertId();$this->upsertWorkspaceMember($workspace,(int)$actor['id'],['manager','operator','reviewer','viewer'],(int)$actor['id']);$event=$this->foundation->recordEffect('harpp.workspace.created','workspace.created',$actor,'harpp_workspace',$workspace,null,['workspace_key'=>$key,'name'=>$name]);}
            elseif($action==='member'){$workspace=(int)($input['workspace_id']??0);$user=(int)($input['user_id']??0);$roles=array_values((array)($input['roles']??[]));if($workspace<=0||$user<=0||!HarppCollaborationPolicy::validRoles($roles))throw new \InvalidArgumentException('Valid workspace_id, user_id, and roles are required.');$this->upsertWorkspaceMember($workspace,$user,$roles,(int)$actor['id']);$event=$this->foundation->recordEffect('harpp.workspace.member_changed','workspace.member_changed',$actor,'harpp_workspace',$workspace,null,['user_id'=>$user,'roles'=>$roles]);}
            elseif($action==='policy'){$workspace=(int)($input['workspace_id']??0);$key=strtolower(trim((string)($input['policy_key']??'')));$name=trim(strip_tags((string)($input['name']??'')));$roles=array_values((array)($input['eligible_roles']??['reviewer']));$quorum=(int)($input['quorum']??1);if($workspace<=0||!preg_match('/^[a-z0-9][a-z0-9._-]{2,190}$/',$key)||$name===''||!HarppCollaborationPolicy::validRoles($roles)||$quorum<1)throw new \InvalidArgumentException('Valid workspace policy fields are required.');$s=$this->database->prepare("INSERT INTO harpp_approval_policies(workspace_id,policy_key,name,eligible_roles,eligible_user_ids,quorum,distinct_actors,exclude_creator,exclude_executor,allow_veto,allow_owner_override,allow_delegation,expires_after_seconds,status,version,created_by,created_at,updated_at) VALUES(:workspace,:key,:name,:roles,:users,:quorum,1,:exclude_creator,:exclude_executor,:veto,:override,:delegation,:expiry,'active',1,:actor,NOW(6),NOW(6))");$s->execute([':workspace'=>$workspace,':key'=>$key,':name'=>$name,':roles'=>json_encode($roles,JSON_THROW_ON_ERROR),':users'=>isset($input['eligible_user_ids'])?json_encode(array_values((array)$input['eligible_user_ids']),JSON_THROW_ON_ERROR):null,':quorum'=>$quorum,':exclude_creator'=>!empty($input['exclude_creator'])?1:0,':exclude_executor'=>!empty($input['exclude_executor'])?1:0,':veto'=>!empty($input['allow_veto'])?1:0,':override'=>!empty($input['allow_owner_override'])?1:0,':delegation'=>!empty($input['allow_delegation'])?1:0,':expiry'=>(int)($input['expires_after_seconds']??0)?:null,':actor'=>(int)$actor['id']]);$policy=(int)$this->database->lastInsertId();$event=$this->foundation->recordEffect('harpp.policy.created','policy.created',$actor,'harpp_approval_policy',$policy,null,['workspace_id'=>$workspace,'policy_key'=>$key,'quorum'=>$quorum]);}
            elseif($action==='delegation'){$workspace=(int)($input['workspace_id']??0);$from=(int)($input['from_user_id']??0);$to=(int)($input['to_user_id']??0);$reason=trim((string)($input['reason']??''));$expires=trim((string)($input['expires_at']??''));if($workspace<=0||$from<=0||$to<=0||$from===$to||$reason===''||strtotime($expires)<=time()||!$this->workspaceMember($workspace,$from)||!$this->workspaceMember($workspace,$to))throw new \InvalidArgumentException('Valid active workspace members, reason, and future expires_at are required.');$s=$this->database->prepare('INSERT INTO harpp_approval_delegations(workspace_id,from_user_id,to_user_id,created_by,reason,valid_from,expires_at) VALUES(:workspace,:from_user,:to_user,:actor,:reason,NOW(6),:expires)');$s->execute([':workspace'=>$workspace,':from_user'=>$from,':to_user'=>$to,':actor'=>(int)$actor['id'],':reason'=>$reason,':expires'=>$expires]);$delegation=(int)$this->database->lastInsertId();$event=$this->foundation->recordEffect('harpp.approval.delegated','approval.delegated',$actor,'harpp_approval_delegation',$delegation,null,['workspace_id'=>$workspace,'from_user_id'=>$from,'to_user_id'=>$to,'expires_at'=>$expires]);}
            else throw new \InvalidArgumentException('Unsupported workspace action.');
            $this->database->commit();return HarppServiceResult::success(['workspace_id'=>$workspace,'approval_policy_id'=>$policy??null,'approval_delegation_id'=>$delegation??null,'action'=>$action],'',[$event],'harpp_workspace',$workspace);
        }catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure($e instanceof \InvalidArgumentException?$e->getMessage():'Unable to manage workspace.',$e instanceof \InvalidArgumentException?422:500);}
    }

    public function listProjects(array $actor,int $workspaceId): HarppServiceResult
    {
        if(!$this->admin($actor)&&!$this->workspaceMember($workspaceId,(int)$actor['id']))return HarppServiceResult::failure('Workspace membership is required.',403);
        $manager=$this->admin($actor)||$this->workspaceRole($workspaceId,(int)$actor['id'],'manager');$sql="SELECT p.id,p.workspace_id,p.project_key,p.name,p.status,p.version,p.created_at,p.updated_at,pm.roles FROM harpp_projects p LEFT JOIN harpp_project_memberships pm ON pm.project_id=p.id AND pm.user_id=:user AND pm.status='active' WHERE p.workspace_id=:workspace".($manager?'':' AND (NOT EXISTS(SELECT 1 FROM harpp_project_memberships any_pm WHERE any_pm.project_id=p.id AND any_pm.status=\'active\') OR pm.user_id IS NOT NULL)').' ORDER BY p.name,p.id';$s=$this->database->prepare($sql);$s->execute([':user'=>(int)$actor['id'],':workspace'=>$workspaceId]);return HarppServiceResult::success(['projects'=>$s->fetchAll(PDO::FETCH_ASSOC)]);
    }

    public function manageProject(array $actor,array $input): HarppServiceResult
    {
        $workspace=(int)($input['workspace_id']??0);if(!$this->admin($actor)&&!$this->workspaceRole($workspace,(int)$actor['id'],'manager'))return HarppServiceResult::failure('Workspace manager access is required.',403);$action=(string)($input['action']??'create');
        try{$this->database->beginTransaction();
            if($action==='create'){$key=strtolower(trim((string)($input['project_key']??'')));$name=trim(strip_tags((string)($input['name']??'')));if(!preg_match('/^[a-z0-9][a-z0-9._-]{2,190}$/',$key)||$name==='')throw new \InvalidArgumentException('Valid project_key and name are required.');$s=$this->database->prepare("INSERT INTO harpp_projects(workspace_id,project_key,name,status,created_by,version,created_at,updated_at) VALUES(:workspace,:key,:name,'active',:actor,1,NOW(6),NOW(6))");$s->execute([':workspace'=>$workspace,':key'=>$key,':name'=>$name,':actor'=>(int)$actor['id']]);$project=(int)$this->database->lastInsertId();$this->upsertProjectMember($project,(int)$actor['id'],['manager','operator','reviewer','viewer']);$event=$this->foundation->recordEffect('harpp.project.created','project.created',$actor,'harpp_project',$project,null,['workspace_id'=>$workspace,'project_key'=>$key,'name'=>$name]);}
            elseif($action==='member'){$project=(int)($input['project_id']??0);$user=(int)($input['user_id']??0);$roles=array_values((array)($input['roles']??[]));if($project<=0||$user<=0||!HarppCollaborationPolicy::validRoles($roles)||!$this->projectInWorkspace($project,$workspace)||!$this->workspaceMember($workspace,$user))throw new \InvalidArgumentException('Project membership may only narrow an active workspace member.');$this->upsertProjectMember($project,$user,$roles);$event=$this->foundation->recordEffect('harpp.project.member_changed','project.member_changed',$actor,'harpp_project',$project,null,['user_id'=>$user,'roles'=>$roles]);}
            else throw new \InvalidArgumentException('Unsupported project action.');
            $this->database->commit();return HarppServiceResult::success(['project_id'=>$project,'workspace_id'=>$workspace,'action'=>$action],'',[$event],'harpp_project',$project);
        }catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure($e instanceof \InvalidArgumentException?$e->getMessage():'Unable to manage project.',$e instanceof \InvalidArgumentException?422:500);}
    }

    public function manageParticipant(array $actor,array $input): HarppServiceResult
    {
        $conversation=(int)($input['conversation_id']??0);$user=(int)($input['user_id']??0);$kind=(string)($input['grant_kind']??'participant');$revoke=filter_var($input['revoke']??false,FILTER_VALIDATE_BOOLEAN);
        if($conversation<=0||$user<=0||!in_array($kind,['participant','private_grant'],true))return HarppServiceResult::failure('Valid conversation_id, user_id, and grant_kind are required.');
        if(!$this->canManageConversation($conversation,$actor))return HarppServiceResult::failure('Conversation manager access is required.',403);
        try{$this->database->beginTransaction();if($revoke){$s=$this->database->prepare('UPDATE harpp_conversation_participants SET revoked_at=NOW(6) WHERE conversation_id=:conversation AND user_id=:user AND grant_kind=:kind AND revoked_at IS NULL');$s->execute([':conversation'=>$conversation,':user'=>$user,':kind'=>$kind]);}
        else{$s=$this->database->prepare('INSERT INTO harpp_conversation_participants(conversation_id,user_id,grant_kind,created_by,created_at,revoked_at) VALUES(:conversation,:user,:kind,:actor,NOW(6),NULL) ON DUPLICATE KEY UPDATE revoked_at=NULL,created_by=VALUES(created_by)');$s->execute([':conversation'=>$conversation,':user'=>$user,':kind'=>$kind,':actor'=>(int)$actor['id']]);}$event=$this->foundation->recordEffect('harpp.participant.changed','participant.changed',$actor,'harpp_conversation',$conversation,null,['user_id'=>$user,'grant_kind'=>$kind,'revoked'=>$revoke]);$this->database->commit();return HarppServiceResult::success(['conversation_id'=>$conversation,'user_id'=>$user,'grant_kind'=>$kind,'revoked'=>$revoke],'',[$event],'harpp_conversation',$conversation);}catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure('Unable to manage participant.',500);}
    }

    public function recordReceipt(array $actor,int $messageId): HarppServiceResult
    {
        if(!$this->foundation->enabled('per_user_receipts'))return HarppServiceResult::success(['enabled'=>false,'recorded'=>false]);
        $user=(int)$actor['id'];$role=(string)($actor['role']??'');$scope=$role==='owner'?'1=1':($role==='admin'?"(c.visibility<>'private' OR c.created_by=:creator_user OR EXISTS(SELECT 1 FROM harpp_conversation_participants pg WHERE pg.conversation_id=c.id AND pg.user_id=:private_user AND pg.grant_kind='private_grant' AND pg.revoked_at IS NULL))":"EXISTS(SELECT 1 FROM harpp_workspace_memberships wm WHERE wm.workspace_id=c.workspace_id AND wm.user_id=:workspace_user AND wm.status='active') AND (c.project_id IS NULL OR EXISTS(SELECT 1 FROM harpp_project_memberships pm WHERE pm.project_id=c.project_id AND pm.user_id=:project_user AND pm.status='active')) AND (c.visibility='workspace' OR c.created_by=:creator_user OR (c.visibility='participants' AND EXISTS(SELECT 1 FROM harpp_conversation_participants cp WHERE cp.conversation_id=c.id AND cp.user_id=:participant_user AND cp.revoked_at IS NULL)) OR (c.visibility='private' AND EXISTS(SELECT 1 FROM harpp_conversation_participants pg WHERE pg.conversation_id=c.id AND pg.user_id=:private_user AND pg.grant_kind='private_grant' AND pg.revoked_at IS NULL)))");$sql='INSERT INTO harpp_message_receipts(message_id,user_id,read_at) SELECT m.id,:receipt_user,NOW(6) FROM harpp_messages m JOIN harpp_conversations c ON c.id=m.conversation_id WHERE m.id=:message AND '.$scope.' ON DUPLICATE KEY UPDATE read_at=VALUES(read_at)';$params=[':receipt_user'=>$user,':message'=>$messageId];foreach(['creator_user','private_user','workspace_user','project_user','participant_user']as$key)if(str_contains($sql,':'.$key))$params[':'.$key]=$user;try{$this->database->beginTransaction();$s=$this->database->prepare($sql);$s->execute($params);$recorded=$s->rowCount()>0;$event=$recorded?$this->foundation->recordEffect('harpp.message.receipt.recorded','message.receipt.recorded',$actor,'harpp_message',$messageId,null,['user_id'=>$user,'read'=>true]):null;$this->database->commit();return HarppServiceResult::success(['enabled'=>true,'message_id'=>$messageId,'recorded'=>$recorded],'',array_values(array_filter([$event])),'harpp_message',$messageId);}catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure('Unable to record message receipt.',500);}
    }

    public function assignDecision(array $actor,array $input): HarppServiceResult
    {
        $decision=(int)($input['decision_id']??0);$user=(int)($input['user_id']??0);$type=(string)($input['assignment_type']??'assignee');$revoke=filter_var($input['revoke']??false,FILTER_VALIDATE_BOOLEAN);$workspace=0;$project=0;if($decision>0){$scope=$this->database->prepare('SELECT workspace_id,project_id FROM harpp_decisions WHERE id=:id');$scope->execute([':id'=>$decision]);$row=$scope->fetch(PDO::FETCH_ASSOC);$workspace=(int)($row['workspace_id']??0);$project=(int)($row['project_id']??0);}if((!$this->admin($actor)&&!$this->workspaceRole($workspace,(int)$actor['id'],'manager'))||$decision<=0||$user<=0||!in_array($type,['assignee','watcher'],true)||!$this->workspaceMember($workspace,$user)||($project>0&&!$this->projectMember($project,$user)))return HarppServiceResult::failure('Assignment targets must be active members of the decision workspace and narrowed project.',403);
        try{$this->database->beginTransaction();if($revoke){$s=$this->database->prepare('UPDATE harpp_decision_assignments SET revoked_at=NOW(6) WHERE decision_id=:decision AND user_id=:user AND assignment_type=:type AND revoked_at IS NULL');$s->execute([':decision'=>$decision,':user'=>$user,':type'=>$type]);}else{$s=$this->database->prepare('INSERT INTO harpp_decision_assignments(decision_id,user_id,assignment_type,created_by,created_at,revoked_at) VALUES(:decision,:user,:type,:actor,NOW(6),NULL) ON DUPLICATE KEY UPDATE revoked_at=NULL,created_by=VALUES(created_by)');$s->execute([':decision'=>$decision,':user'=>$user,':type'=>$type,':actor'=>(int)$actor['id']]);}$event=$this->foundation->recordEffect('harpp.decision.assignment_changed','decision.assignment_changed',$actor,'harpp_decision',$decision,null,['user_id'=>$user,'assignment_type'=>$type,'revoked'=>$revoke]);$this->database->commit();return HarppServiceResult::success(['decision_id'=>$decision,'user_id'=>$user,'assignment_type'=>$type,'revoked'=>$revoke],'',[$event],'harpp_decision',$decision);}catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure('Unable to assign decision.',500);}
    }

    public function approveDecision(array $actor,array $input): HarppServiceResult
    {
        if(!$this->foundation->enabled('approval_policies'))return HarppServiceResult::failure('Approval policies are disabled.',409,'feature_disabled');$decision=(int)($input['decision_id']??0);$vote=(string)($input['vote']??'approve');$reason=trim((string)($input['reason']??''));if($decision<=0||!in_array($vote,['approve','veto'],true)||$reason==='')return HarppServiceResult::failure('Valid decision_id, vote, and reason are required.');
        $eligible=$this->database->prepare("SELECT s.policy_json,s.created_at snapshot_at,d.created_by,wm.roles FROM harpp_decision_policy_snapshots s JOIN harpp_decisions d ON d.id=s.decision_id JOIN harpp_workspace_memberships wm ON wm.workspace_id=d.workspace_id AND wm.user_id=:user AND wm.status='active' WHERE d.id=:decision");$eligible->execute([':user'=>(int)$actor['id'],':decision'=>$decision]);$eligibility=$eligible->fetch(PDO::FETCH_ASSOC);if(!is_array($eligibility))return HarppServiceResult::failure('An active workspace policy snapshot is required.',403);$policy=(array)json_decode((string)$eligibility['policy_json'],true);$roles=(array)json_decode((string)$eligibility['roles'],true);$eligibleRoles=(array)json_decode((string)($policy['eligible_roles']??'[]'),true);$eligibleUsers=(array)json_decode((string)($policy['eligible_user_ids']??'[]'),true);$roleMatch=array_intersect($roles,$eligibleRoles)!==[];$userMatch=in_array((int)$actor['id'],array_map('intval',$eligibleUsers),true);if(!$roleMatch&&!$userMatch)return HarppServiceResult::failure('Actor is not eligible under the snapshotted policy.',403);if(!empty($policy['exclude_creator'])&&(int)$eligibility['created_by']===(int)$actor['id'])return HarppServiceResult::failure('Creator self-approval is excluded.',409,'separation_of_duties');if((int)($policy['expires_after_seconds']??0)>0&&strtotime((string)$eligibility['snapshot_at'])+(int)$policy['expires_after_seconds']<time())return HarppServiceResult::failure('Approval policy snapshot has expired.',409,'approval_expired');
        $delegatedBy=(int)($input['delegated_by']??0);if($delegatedBy>0){if(empty($policy['allow_delegation']))return HarppServiceResult::failure('The snapshotted policy forbids delegation.',409,'delegation_forbidden');$delegation=$this->database->prepare('SELECT 1 FROM harpp_approval_delegations ad JOIN harpp_decisions d ON d.workspace_id=ad.workspace_id WHERE d.id=:decision AND ad.from_user_id=:from_user AND ad.to_user_id=:to_user AND ad.revoked_at IS NULL AND ad.valid_from<=NOW(6) AND ad.expires_at>NOW(6)');$delegation->execute([':decision'=>$decision,':from_user'=>$delegatedBy,':to_user'=>(int)$actor['id']]);if($delegation->fetchColumn()===false)return HarppServiceResult::failure('No active approval delegation exists.',403,'delegation_invalid');}
        try{$this->database->beginTransaction();$s=$this->database->prepare('INSERT INTO harpp_decision_approvals(decision_id,user_id,vote,reason,delegated_by,created_at) VALUES(:decision,:user,:vote,:reason,:delegated,NOW(6))');$s->execute([':decision'=>$decision,':user'=>(int)$actor['id'],':vote'=>$vote,':reason'=>$reason,':delegated'=>$delegatedBy?:null]);$event=$this->foundation->recordEffect('harpp.decision.approved','decision.approved',$actor,'harpp_decision',$decision,null,['vote'=>$vote,'delegated_by'=>$delegatedBy?:null],$reason);$this->database->commit();return HarppServiceResult::success(['decision_id'=>$decision,'vote'=>$vote,'delegated_by'=>$delegatedBy?:null],'',[$event],'harpp_decision',$decision);}catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure(str_contains(strtolower($e->getMessage()),'duplicate')?'This reviewer already voted.':'Unable to record approval.',str_contains(strtolower($e->getMessage()),'duplicate')?409:500,str_contains(strtolower($e->getMessage()),'duplicate')?'duplicate_vote':'approval_failed');}
    }

    public function approvalSatisfied(int $decisionId,?int $executorId=null): bool
    {
        if(!$this->foundation->enabled('approval_policies'))return true;$s=$this->database->prepare('SELECT s.policy_json,d.created_by FROM harpp_decision_policy_snapshots s JOIN harpp_decisions d ON d.id=s.decision_id WHERE s.decision_id=:id');$s->execute([':id'=>$decisionId]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($row))return false;$v=$this->database->prepare('SELECT user_id,vote FROM harpp_decision_approvals WHERE decision_id=:id ORDER BY id');$v->execute([':id'=>$decisionId]);return HarppCollaborationPolicy::approvalSatisfied((array)json_decode((string)$row['policy_json'],true),$v->fetchAll(PDO::FETCH_ASSOC),(int)$row['created_by'],$executorId);
    }

    public function reviewerEligible(int $decisionId,int $userId): bool
    {
        $s=$this->database->prepare("SELECT s.policy_json,wm.roles FROM harpp_decision_policy_snapshots s JOIN harpp_decisions d ON d.id=s.decision_id JOIN harpp_workspace_memberships wm ON wm.workspace_id=d.workspace_id AND wm.user_id=:user AND wm.status='active' WHERE s.decision_id=:decision");$s->execute([':user'=>$userId,':decision'=>$decisionId]);$row=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($row))return false;$policy=(array)json_decode((string)$row['policy_json'],true);$roles=(array)json_decode((string)$row['roles'],true);$eligibleRoles=(array)json_decode((string)($policy['eligible_roles']??'[]'),true);$eligibleUsers=array_map('intval',(array)json_decode((string)($policy['eligible_user_ids']??'[]'),true));return array_intersect($roles,$eligibleRoles)!==[]||in_array($userId,$eligibleUsers,true);
    }

    public function notificationPreferences(array $actor,array $input): HarppServiceResult
    {
        $event=trim((string)($input['event_type']??''));$channel=(string)($input['channel']??'in_app');if($event===''){$s=$this->database->prepare('SELECT workspace_id,event_type,channel,enabled,version,updated_at FROM harpp_notification_preferences WHERE user_id=:user ORDER BY event_type,channel');$s->execute([':user'=>(int)$actor['id']]);return HarppServiceResult::success(['preferences'=>$s->fetchAll(PDO::FETCH_ASSOC)]);}if(!preg_match('/^[a-z][a-z0-9._-]{2,99}$/',$event)||!in_array($channel,['push','in_app'],true))return HarppServiceResult::failure('Valid event_type and channel are required.');$workspace=(int)($input['workspace_id']??0);$enabled=filter_var($input['enabled']??true,FILTER_VALIDATE_BOOLEAN);if($workspace>0&&!$this->workspaceMember($workspace,(int)$actor['id']))return HarppServiceResult::failure('Workspace membership is required.',403);try{$this->database->beginTransaction();$s=$this->database->prepare('INSERT INTO harpp_notification_preferences(user_id,workspace_id,event_type,channel,enabled,version,updated_at) VALUES(:user,NULLIF(:workspace,0),:event,:channel,:enabled,1,NOW(6)) ON DUPLICATE KEY UPDATE enabled=VALUES(enabled),version=version+1');$s->execute([':user'=>(int)$actor['id'],':workspace'=>$workspace,':event'=>$event,':channel'=>$channel,':enabled'=>$enabled?1:0]);$find=$this->database->prepare('SELECT id FROM harpp_notification_preferences WHERE user_id=:user AND workspace_id<=>NULLIF(:workspace,0) AND event_type=:event AND channel=:channel');$find->execute([':user'=>(int)$actor['id'],':workspace'=>$workspace,':event'=>$event,':channel'=>$channel]);$preference=(int)$find->fetchColumn();$effect=$this->foundation->recordEffect('harpp.notification.preference_changed','notification.preference_changed',$actor,'harpp_notification_preference',$preference,null,['workspace_id'=>$workspace?:null,'event_type'=>$event,'channel'=>$channel,'enabled'=>$enabled]);$this->database->commit();return HarppServiceResult::success(['event_type'=>$event,'channel'=>$channel,'enabled'=>$enabled],'',[$effect],'harpp_notification_preference',$preference);}catch(Throwable $e){if($this->database->inTransaction())$this->database->rollBack();return HarppServiceResult::failure('Unable to save notification preference.',500);}
    }

    public function snapshotPolicy(int $decisionId,int $policyId): void
    {
        if(!$this->foundation->enabled('approval_policies')||$policyId<=0)return;$s=$this->database->prepare("SELECT p.* FROM harpp_approval_policies p JOIN harpp_decisions d ON d.workspace_id=p.workspace_id WHERE p.id=:id AND d.id=:decision AND p.status='active'");$s->execute([':id'=>$policyId,':decision'=>$decisionId]);$policy=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($policy))throw new \InvalidArgumentException('Active approval policy in the decision workspace was not found.');$json=json_encode($policy,JSON_THROW_ON_ERROR);$i=$this->database->prepare('INSERT INTO harpp_decision_policy_snapshots(decision_id,source_policy_id,policy_version,policy_json,created_at) VALUES(:decision,:policy,:version,:json,NOW(6))');$i->execute([':decision'=>$decisionId,':policy'=>$policyId,':version'=>(int)$policy['version'],':json'=>$json]);
    }

    /** Eligible notification recipients; preferences narrow fanout but never grant visibility. */
    public function notificationRecipients(int $workspaceId,?int $conversationId,string $eventType,int $excludeUser=0): array
    {
        $sql="SELECT DISTINCT u.id FROM harpp_users u LEFT JOIN harpp_workspace_memberships wm ON wm.user_id=u.id AND wm.workspace_id=:membership_workspace AND wm.status='active' LEFT JOIN harpp_notification_preferences np ON np.user_id=u.id AND (np.workspace_id=:preference_workspace OR np.workspace_id IS NULL) AND np.event_type=:event AND np.channel='in_app' WHERE u.is_active=1 AND u.deleted_at IS NULL AND u.id<>:exclude AND (u.role='owner' OR wm.id IS NOT NULL) AND COALESCE(np.enabled,1)=1";$params=[':membership_workspace'=>$workspaceId,':preference_workspace'=>$workspaceId,':event'=>$eventType,':exclude'=>$excludeUser];
        if($conversationId!==null){$sql.=" AND EXISTS(SELECT 1 FROM harpp_conversations c WHERE c.id=:conversation AND (u.role='owner' OR ((c.project_id IS NULL OR EXISTS(SELECT 1 FROM harpp_project_memberships pm WHERE pm.project_id=c.project_id AND pm.user_id=u.id AND pm.status='active')) AND (c.visibility='workspace' OR (c.visibility='participants' AND (c.created_by=u.id OR EXISTS(SELECT 1 FROM harpp_conversation_participants cp WHERE cp.conversation_id=c.id AND cp.user_id=u.id AND cp.revoked_at IS NULL))) OR (c.visibility='private' AND (c.created_by=u.id OR EXISTS(SELECT 1 FROM harpp_conversation_participants pg WHERE pg.conversation_id=c.id AND pg.user_id=u.id AND pg.grant_kind='private_grant' AND pg.revoked_at IS NULL))))))";$params[':conversation']=$conversationId;}
        $sql.=' ORDER BY u.id';$s=$this->database->prepare($sql);$s->execute($params);return array_map('intval',$s->fetchAll(PDO::FETCH_COLUMN));
    }

    private function upsertWorkspaceMember(int $workspace,int $user,array $roles,int $creator):void{$s=$this->database->prepare("INSERT INTO harpp_workspace_memberships(workspace_id,user_id,roles,status,created_by,version,created_at,updated_at) VALUES(:workspace,:user,:roles,'active',:creator,1,NOW(6),NOW(6)) ON DUPLICATE KEY UPDATE roles=VALUES(roles),status='active',version=version+1");$s->execute([':workspace'=>$workspace,':user'=>$user,':roles'=>json_encode($roles,JSON_THROW_ON_ERROR),':creator'=>$creator]);}
    private function upsertProjectMember(int $project,int $user,array $roles):void{$s=$this->database->prepare("INSERT INTO harpp_project_memberships(project_id,user_id,roles,status,created_at) VALUES(:project,:user,:roles,'active',NOW(6)) ON DUPLICATE KEY UPDATE roles=VALUES(roles),status='active'");$s->execute([':project'=>$project,':user'=>$user,':roles'=>json_encode($roles,JSON_THROW_ON_ERROR)]);}
    private function workspaceMember(int $workspace,int $user):bool{$s=$this->database->prepare("SELECT 1 FROM harpp_workspace_memberships WHERE workspace_id=:workspace AND user_id=:user AND status='active'");$s->execute([':workspace'=>$workspace,':user'=>$user]);return$s->fetchColumn()!==false;}
    private function workspaceRole(int $workspace,int $user,string $role):bool{$s=$this->database->prepare("SELECT 1 FROM harpp_workspace_memberships WHERE workspace_id=:workspace AND user_id=:user AND status='active' AND JSON_CONTAINS(roles,:role)");$s->execute([':workspace'=>$workspace,':user'=>$user,':role'=>json_encode($role)]);return$s->fetchColumn()!==false;}
    private function projectInWorkspace(int $project,int $workspace):bool{$s=$this->database->prepare('SELECT 1 FROM harpp_projects WHERE id=:project AND workspace_id=:workspace');$s->execute([':project'=>$project,':workspace'=>$workspace]);return$s->fetchColumn()!==false;}
    private function projectMember(int $project,int $user):bool{$s=$this->database->prepare("SELECT 1 FROM harpp_project_memberships WHERE project_id=:project AND user_id=:user AND status='active'");$s->execute([':project'=>$project,':user'=>$user]);return$s->fetchColumn()!==false;}
    private function canManageConversation(int $conversation,array $actor):bool{if($this->admin($actor))return true;$s=$this->database->prepare("SELECT 1 FROM harpp_conversations c JOIN harpp_workspace_memberships wm ON wm.workspace_id=c.workspace_id AND wm.user_id=:member_user AND wm.status='active' WHERE c.id=:conversation AND JSON_CONTAINS(wm.roles,'\"manager\"')");$s->execute([':conversation'=>$conversation,':member_user'=>(int)$actor['id']]);return$s->fetchColumn()!==false;}
    private function admin(array $actor):bool{return(int)($actor['id']??0)>0&&in_array((string)($actor['role']??''),['owner','admin'],true);}
}
